# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "Ubuntu-2410"
  config.vm.network :private_network, ip: "192.168.56.8"
  config.vm.hostname = "drupal.test"
  config.ssh.private_key_path = "~/.ssh/id_ed25519"
  config.ssh.insert_key = false

  config.vm.provider :virtualbox do |v|
    v.memory = 2048
  end

  # Ansible provisioning.
#  config.vm.provision "ansible" do |ansible|
   # ansible.playbook = "playbook.yml"
 # end
end
